import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Arabia Fees System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-100">
        <Toaster position="top-right"/>
        <div className="w-full flex justify-center py-6 lg:sticky lg:top-0 top-auto bottom-0 fixed z-10">
        <Navbar/>
        </div>
        {children}
        </body>
    </html>
  );
}
