import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import { SessionWrapper } from "@/components/SessionWrapper/SessionWrapper";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Arabia Fees System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-indigo-200 via-purple-200 to-pink-200 min-h-screen">
        <SessionWrapper>
          <Toaster position="top-right" />
          <Navbar/>
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
