export const studentDrawerMappingKeys: { [key: string]: string } = {
    studentName: 'Student Name',
    FatherName: 'Father Name',
    age: 'Age',
    grade: 'Grade',
    TshirtSize: 'T-Shirt Size',
    activity: 'Activity',
    createdAt: 'Created Date',
    camp: 'Camp Number',
    group: 'Group',
    report: 'Report',
    status: 'Status',
    subCamp: 'Sub Camp',
    updatedAt: 'Update Date',
};