import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from "react-hot-toast";
import { SessionWrapper } from "@/components/SessionWrapper/SessionWrapper";
import Navbar from "@/components/Navbar/Navbar";
import { Suspense } from "react";
import { FallBackComponent } from "@/components/FallBackComponent/FallBackComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Arabia Fees System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // bg-gradient-to-r from-indigo-200 via-purple-200 to-pink-200
    <html lang="en">
      <body>
        <Suspense fallback={<FallBackComponent/>}>
          <div className="relative bg-camping-image bg-blend-darken bg-cover bg-no-repeat min-h-screen">
            <div className="absolute inset-0 bg-black opacity-50"></div>
            <SessionWrapper>
              <Toaster position="top-right" />
              <Navbar />
              <div className="relative z-10">{children}</div>
            </SessionWrapper>
          </div>
        </Suspense>
      </body>
    </html>
  );
}
